In [3]:
#createing numpy
import numpy as np

In [4]:
np.array([2,3,4])#1D array

array([2, 3, 4])

In [4]:
a=np.array([2,34,56,422])
print(a)
type(a)

[  2  34  56 422]


numpy.ndarray

In [5]:
#2D array(matrix)
new=np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [6]:
#3D ---#tensor 
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [7]:
np.array([11,23,44],dtype=float)

array([11., 23., 44.])

In [8]:
np.array([11,23,44],dtype=bool)#here true becoz ,python treats non zero

array([ True,  True,  True])

In [9]:
np.array([11,23,44],dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [10]:
#arange
np.arange(1,25)  #1-included ,25 - last one got excluded 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
np.arange(1,25,2)#strides -->alternate numbers 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
#reshape
np.arange(1,11).reshape(5,2) #contered 5 rows,2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
np.arange(1,11).reshape(2,5)#conveted 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
#one&zeros
np.ones((3,4)) #we have to mention iside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#Another type --> random()
np.random.random((4,3))

array([[0.80963228, 0.28941062, 0.01773425],
       [0.57256185, 0.75743087, 0.92710698],
       [0.13800966, 0.09364766, 0.34263604],
       [0.62827788, 0.68011329, 0.72404312]])

In [20]:
#linspace 
np.linspace(-10,10,10)  #here:lower range ,upper range ,number of items to get
#here start value -10 ,and end value 10 (which is included) ,then num=10 
#then here formula (end-start/num-1) 10-(-10)/10-1=20/9=2.22222 ,which is difference

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [22]:
#identity
#creating the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [5]:
#array attributes
a1=np.arange(10)#1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a2=np.arange(12,dtype=float).reshape(3,4)#matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
a3=np.arange(8).reshape(2,2,2)#3D-->Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim
a1.ndim

In [8]:
a2.ndim

2

In [9]:
a3.ndim

3

In [10]:
#shape
a1.shape #1D array has 10 items 

(10,)

In [11]:
a2.shape #3rows and 4 columns 

(3, 4)

In [12]:
a3.shape  #first 2 says it consists of 2D arrays,2,2 gives noof rows no of colomns 

(2, 2, 2)

In [13]:
#size
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
a3.size #it has 8 items .like shape :2,2,2=8

8

In [15]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
a2.size

12

In [17]:
a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# itemsize
# Memory occupied by the item

In [19]:
a1.itemsize #bytes

8

In [20]:
a2.itemsize #float 64 gives=8bytes

8

In [21]:
a3.itemsize #integer 64gives =8bytes 

8

# dtype

In [47]:

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


# changing  datatype 

In [27]:
#astype 
x= np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [28]:
x.astype(int)

array([33, 22,  2])

# ARRAY OPERATIONS

In [30]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [31]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operations

In [33]:
#arithematic
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [34]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [35]:
#multiplication
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [36]:
#power
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [37]:
#modulus
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# Relation operators

In [38]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
z2>2 # if 2 is greater than every element ,then gives true

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
z2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# vector operations


In [41]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
#arthematic 
z1+z2 #both numpy array shape is same ,we can add item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [44]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [45]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [46]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# array functions

In [48]:
k1=np.random.random((3,3))
k1=np.round(k1*100)
k1


array([[88., 93.,  9.],
       [ 6., 20., 52.],
       [63., 23., 21.]])

In [49]:
#max
np.max(k1)

np.float64(93.0)

In [50]:
#min
np.min(k1)

np.float64(6.0)

In [51]:
#sum
np.sum(k1)

np.float64(375.0)

In [52]:
#prod   ---> multiplication
np.prod(k1)

np.float64(13985577365760.0)

# In numpy 
# 0=column,1=row

In [54]:
#if we want maximum of every row
np.max(k1,axis=1)

array([93., 52., 63.])

In [55]:
#maximum of every column
np.max(k1,axis=0)

array([88., 93., 52.])

In [56]:
#product of every column
np.prod(k1,axis=0)

array([33264., 42780.,  9828.])

In [ ]:
# statistics related functions